Models/Module.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Oesia.Models
{
    public class Module
    {
        public long Id { get; set; }
        public string ModuleId { get; set; }
        public string Description { get; set; }
        public double EstimatedHours { get; set; }
        public double ElapsedHours { get; set; }
        public double PendingHours { get; set; }
        public string Status { get; set; }
        public List<Submodule> Submodules { get; set; }
       
        public long ProjectId { get; set; }
        public Project Project { get; set; }
    }
}

Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Oesia.Data;
using Oesia.Models;

namespace Oesia.Controllers
{
    [Authorize]
    public class ModulesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ModulesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Modules
        public async Task<IActionResult> Index()
        {
            return View(await _context.Module.ToListAsync());
        }

        //[Route("ModuleJson")]
        //[ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        //// GET: Modules
        //public async Task<IActionResult> ModuleJson()
        //{
        //    return Json(await _context.Module.ToListAsync());
        //}


        // GET: Modules/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await _context.Module
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // GET: Modules/Create
        [Authorize(Roles = "Project manager")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Modules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Project manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ModuleId,Description,EstimatedHours,ElapsedHours,PendingHours,Status,ProjectId")] Module @module)
        {
            module.PendingHours = module.EstimatedHours;
            module.Status = "At risk";
            if (ModelState.IsValid)
            {
                _context.Add(@module);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@module);
        }

        // GET: Modules/Edit/5
        [Authorize(Roles = "Project manager")]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await _context.Module.FindAsync(id);
            if (@module == null)
            {
                return NotFound();
            }
            return View(@module);
        }

        // POST: Modules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Project manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,ModuleId,Description,EstimatedHours,ElapsedHours,PendingHours,Status,ProjectId")] Module @module)
        {
            if (id != @module.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@module);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModuleExists(@module.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@module);
        }

        // GET: Modules/Delete/5
        [Authorize(Roles = "Project manager")]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @module = await _context.Module
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@module == null)
            {
                return NotFound();
            }

            return View(@module);
        }

        // POST: Modules/Delete/5
        [Authorize(Roles = "Project manager")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var @module = await _context.Module.FindAsync(id);
            _context.Module.Remove(@module);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModuleExists(long id)
        {
            return _context.Module.Any(e => e.Id == id);
        }
    }
}

Controllers/SubmodulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Oesia.Data;
using Oesia.Models;

namespace Oesia.Controllers
{
    [Authorize]
    public class SubmodulesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SubmodulesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Submodules
        public async Task<IActionResult> Index()
        {
            return View(await _context.Submodule.ToListAsync());
        }

        // GET: Submodules/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var submodule = await _context.Submodule
                .FirstOrDefaultAsync(m => m.Id == id);
            if (submodule == null)
            {
                return NotFound();
            }

            return View(submodule);
        }

        // GET: Submodules/Create
        [Authorize(Roles = "Project manager")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Submodules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Project manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SubmoduleId,Description,EstimatedHours,ElapsedHours,PendingHours,Status,ModuleId")] Submodule submodule)
        {
            submodule.PendingHours = submodule.EstimatedHours;
            submodule.Status = "At risk";

            if (ModelState.IsValid)
            {
                _context.Add(submodule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(submodule);
        }

        // GET: Submodules/Edit/5
        [Authorize(Roles = "Project manager")]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var submodule = await _context.Submodule.FindAsync(id);
            if (submodule == null)
            {
                return NotFound();
            }
            return View(submodule);
        }

        // POST: Submodules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Project manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,SubmoduleId,Description,EstimatedHours,ElapsedHours,PendingHours,Status,ModuleId")] Submodule submodule)
        {
            if (id != submodule.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(submodule);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubmoduleExists(submodule.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(submodule);
        }

        // GET: Submodules/Delete/5
        [Authorize(Roles = "Project manager")]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var submodule = await _context.Submodule
                .FirstOrDefaultAsync(m => m.Id == id);
            if (submodule == null)
            {
                return NotFound();
            }

            return View(submodule);
        }

        // POST: Submodules/Delete/5
        [Authorize(Roles = "Project manager")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var submodule = await _context.Submodule.FindAsync(id);
            _context.Submodule.Remove(submodule);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubmoduleExists(long id)
        {
            return _context.Submodule.Any(e => e.Id == id);
        }
    }
}

Views/Modules/Create.cshtml
@model Oesia.Models.Module
@inject Oesia.Services.OesiaServices Services

@{
    ViewData["Title"] = "Create";
}

<hr />
<div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-6 col-xs-offset-3">
        <h2>Create New Module</h2>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ModuleId" class="control-label"></label>
                <input asp-for="ModuleId" class="form-control" />
                <span asp-validation-for="ModuleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Assign it to a project</label>
                <p></p>
                <select asp-for="ProjectId">
                    <option value="">Choose a project...</option>
                    @foreach (Project item in Services.GetProjectsDB())
                    {
                        <option value="@item.Id">@item.ProjectId</option>
                    }
                </select>
                <span class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedHours" class="control-label"></label>
                <input asp-for="EstimatedHours" class="form-control" />
                <span asp-validation-for="EstimatedHours" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="ElapsedHours" class="control-label"></label>
                <input asp-for="ElapsedHours" class="form-control" />
                <span asp-validation-for="ElapsedHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PendingHours" class="control-label"></label>
                <input asp-for="PendingHours" class="form-control" />
                <span asp-validation-for="PendingHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
                @*<a class="btn btn-default" asp-area="" asp-controller="Submodules" asp-action="Create">Add Submodule</a>*@
            </div>
        </form>
        <div>
            <a asp-action="Index">Back to List Of Modules</a>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Modules/Delete.cshtml
@model Oesia.Models.Module

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Module</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ModuleId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModuleId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EstimatedHours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EstimatedHours)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ElapsedHours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ElapsedHours)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PendingHours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PendingHours)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Modules/Details.cshtml
@model Oesia.Models.Module

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Module</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ModuleId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModuleId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EstimatedHours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EstimatedHours)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ElapsedHours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ElapsedHours)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PendingHours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PendingHours)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Modules/Edit.cshtml
@model Oesia.Models.Module

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Module</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ModuleId" class="control-label"></label>
                <input asp-for="ModuleId" class="form-control" />
                <span asp-validation-for="ModuleId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstimatedHours" class="control-label"></label>
                <input asp-for="EstimatedHours" class="form-control" />
                <span asp-validation-for="EstimatedHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="ElapsedHours" class="control-label"></label>*@
                <input type="hidden" asp-for="ElapsedHours" class="form-control" />
                @*<span asp-validation-for="ElapsedHours" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                @*<label asp-for="PendingHours" class="control-label"></label>*@
                <input type="hidden" asp-for="PendingHours" class="form-control" />
                @*<span asp-validation-for="PendingHours" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                @*<label asp-for="TaskId" class="control-label"></label>*@
                <input type="hidden" asp-for="ProjectId" class="form-control" readonly="readonly" value="@Model.ProjectId" />
                @*<span asp-validation-for="TaskId" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                @*<label asp-for="Status" class="control-label"></label>*@
                <input type="hidden" asp-for="Status" class="form-control" readonly="readonly" />
                @*<span asp-validation-for="Status" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Modules/Index.cshtml
@model IEnumerable<Oesia.Models.Module>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ModuleId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstimatedHours)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ElapsedHours)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PendingHours)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ModuleId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstimatedHours)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ElapsedHours)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PendingHours)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>